server:
  port: 2001

spring:
  application:
    name: logins

  datasource:
    url: jdbc:postgresql://localhost:5432/login-db
    username: postgres
    password: ${DB_PASSWORD:jyoti}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Login Service
    version: 1.0
    description: Login REST API
    author: Naveen

logging:
  file:
    name: C:/applications/logins/logs/logins.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

  level:
    root: INFO